# Generated by Django 5.1.6 on 2025-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='super_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=250, null=True)),
                ('role', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'super_admin',
            },
        ),
    ]
