# Generated by Django 5.1.6 on 2025-05-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
