# Generated by Django 5.1.6 on 2025-05-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_user_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_admin',
        ),
        migrations.AlterModelTable(
            name='user_admin',
            table='user_admin',
        ),
    ]
